// <auto-generated />
using System;
using GeneralLabSolutions.InfraStructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneralLabSolutions.InfraStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasComment("Descrição da categoria do produto");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Descricao");

                    b.ToTable("CategoriaProduto");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusDoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDePessoa")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Documento");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Cliente_Nome");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("EmailAlternativo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<string>("TelefoneAlternativo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<string>("TipoDeContato")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Contato_Email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Contato_Nome");

                    b.ToTable("Contato", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.EstadoDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemPedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoId")
                        .IsUnique();

                    b.ToTable("EstadoDoItem", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusDoFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDePessoa")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("IX_Fornecedor_Documento");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Fornecedor_Email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Fornecedor_Nome");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Fornecedor", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.GerenciadorDeFluxoKanban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_GerenciadorDeFluxoKanban_Status");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IX_GerenciadorDeFluxoKanban_Titulo");

                    b.ToTable("GerenciadorDeFluxoKanban");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeDoProduto")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasComment("Descrição do produto");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NomeDoProduto")
                        .HasDatabaseName("IX_ItemPedido_NomeDoProduto");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedido", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.MembroEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_MembroEquipe_Nome");

                    b.ToTable("MembroEquipe");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime")
                        .HasColumnName("DataPedido");

                    b.Property<string>("StatusDoPedido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Orcamento");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.PessoaContato", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PessoaId", "ContatoId");

                    b.HasIndex("ContatoId");

                    b.ToTable("PessoaContato");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.PessoaTelefone", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PessoaId", "TelefoneId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("PessoaTelefone");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataDeValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasComment("Descrição do produto");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("NCM");

                    b.Property<string>("StatusDoProduto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Dropshipping");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorUnitario");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Produto_Codigo");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("IX_Produto_Descricao");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("Ncm")
                        .IsUnique()
                        .HasDatabaseName("IX_Produto_Ncm");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoDeTelefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DDD")
                        .HasDatabaseName("IX_Telefone_DDD");

                    b.HasIndex("Numero")
                        .HasDatabaseName("IX_Telefone_Numero");

                    b.ToTable("Telefone", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusDoVendedor")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDePessoa")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("IX_Vendedor_Documento");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Vendedor_Email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Vendedor_Nome");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Percentual")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoDescontoVoucher")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("IX_Voucher_Codigo");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("GerenciadorDeFluxoKanbanMembroEquipe", b =>
                {
                    b.Property<Guid>("MembrosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TarefasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MembrosId", "TarefasId");

                    b.HasIndex("TarefasId");

                    b.ToTable("TarefaMembro", (string)null);
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("GeneralLabSolutions.Domain.Entities.Cliente", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.EstadoDoItem", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.ItemPedido", "ItemPedido")
                        .WithOne("EstadoDoItem")
                        .HasForeignKey("GeneralLabSolutions.Domain.Entities.EstadoDoItem", "ItemPedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ItemPedido");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("GeneralLabSolutions.Domain.Entities.Fornecedor", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Voucher", "Voucher")
                        .WithMany("Pedidos")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.PessoaContato", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Contato", "Contato")
                        .WithMany("PessoasContatos")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("PessoasContatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.PessoaTelefone", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("PessoasTelefones")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Telefone", "Telefone")
                        .WithMany("PessoasTelefones")
                        .HasForeignKey("TelefoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Produto", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.CategoriaProduto", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Vendedor", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("GeneralLabSolutions.Domain.Entities.Vendedor", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GerenciadorDeFluxoKanbanMembroEquipe", b =>
                {
                    b.HasOne("GeneralLabSolutions.Domain.Entities.MembroEquipe", null)
                        .WithMany()
                        .HasForeignKey("MembrosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneralLabSolutions.Domain.Entities.GerenciadorDeFluxoKanban", null)
                        .WithMany()
                        .HasForeignKey("TarefasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Contato", b =>
                {
                    b.Navigation("PessoasContatos");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.ItemPedido", b =>
                {
                    b.Navigation("EstadoDoItem")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("PessoasContatos");

                    b.Navigation("PessoasTelefones");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Telefone", b =>
                {
                    b.Navigation("PessoasTelefones");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Vendedor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("GeneralLabSolutions.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
